### ISSUE TITLE
article(angular2): Developing a Tabs component in Angular 2

### ISSUE THREAD

**Issue by PascalPrecht** [thoughtram/blog#24]
Update to alpha.34

- @Parent is deprecated
- Either use parent injector or @Query

**Comment by Hotell** [comment]
I've created new demos with your proposed changes:

* using `@Query` decorator http://plnkr.co/edit/UBMcWqLwuPZuunjEruLa?p=preview
* using `DI` http://plnkr.co/edit/1no1sjZ9Lkv4glsUFnnU?p=preview

`@Query`  version is kind of hack, because `QueryList` doesn't provide interface as it should ( EventEmitter which is returned on calling #changes getter doesn't return Observable ) - Angular 2 bug

I would like to update this blog post, but can't decide, what to put there. Just update ( via Parent Inejctor ) or add new content about `@Query` version or both?

What do you think?
thanks!

**Comment by PascalPrecht** [comment]
@Hotell hey thank you for jumping on this and sorry for the long wait. We were very busy with AngularConnect.

It's not longer `@Query` and `@ViewQuery`. Things are moving fast. We now use `@ContentChildren`, `@ContentChild`, `@ViewChildren` and `@ViewChild`.

Wanna give it another try?

**Comment by Hotell** [comment]
No problem at all. Yeah I've noticed the changes. Sure I'll update it during this weekend. thx

**Comment by Hotell** [comment]
updated

* using `@ContentChildren` with `#afterContentInit` hook http://plnkr.co/edit/Y5VVAATuKJXhMz69SxfF?p=preview
* using `Parent Injector` ( angular 1 like tabs style ) http://plnkr.co/edit/1no1sjZ9Lkv4glsUFnnU?p=preview

**Comment by PascalPrecht** [comment]
@Hotell thank you! Do you mind updating the article as well? :)

And then you can send a PR!

**Comment by Hotell** [comment]
will do! thanks

**Comment by PascalPrecht** [comment]
Hey, any updates on this? :)

**Comment by Hotell** [comment]
I'm on vacation till 22.11. but I'll try to submit PR asap. Sry for the delay.

**Comment by PascalPrecht** [comment]
Gotcha, enjoy you off-time!

**Comment by Hotell** [comment]
Will do. Thanks! :)
